name: Generate PAC

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: update
        run: ./doall.sh

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Push lists
        uses: EndBug/add-and-commit@v9
        with:
          add: './result/proxy-host-*.pac'
          author_name: GitHub Action
          author_email: githubaction@githubaction.com
          message: 'Update PAC files ${{ steps.date.outputs.date }}'
          push: true
